### ISSUE TITLE
Workers all run on same node.

### ISSUE THREAD

**Issue by coledie** [microsoft/ray-on-aml#34]
Hello, I've got a bug where I start a job with multiple nodes and multiple workers using ray_on_aml
* When I start a job with placement_strategy="SPREAD", print(ray.get_runtime_context().node_id) reads as the same node for each worker - it should be different nodes for each worker.
* When I start a job with placement_strategy="STRICT_SPREAD", the job reads pending and does not start.
Notably, ray.cluster_resources() shows that one node is alive and one node is not when I start the job.

```python
    ws = Workspace.from_config()
    ray_on_aml = Ray_On_AML(ws=ws, compute_cluster="gpu-cluster", maxnode=2)
    ray = ray_on_aml.getRay(ci_is_head=True, num_node=2)

    trainer = TorchTrainer(
        train_func,
        train_loop_config={
            "num_epochs": 10,
            "feature_idx": 0,
            "feature_dim": 1433,
            "label_idx": 1,
            "label_dim": 1,
            "num_classes": 7,
        },
        run_config=RunConfig(),
        scaling_config=ScalingConfig(
            num_workers=2, placement_strategy="SPREAD"
        ),
    )
    result = trainer.fit()
    ray_on_aml.shutdown()
```

**Comment by james-tn** [comment]
Can you check if all workers started correctly by looking at the log in AzureML job?

**Comment by coledie** [comment]
I believe yes, I can see output from both workers in the terminal. logs/worker_0 and logs/worker_1 are empty. user_logs/std_log_process_0.txt and user_logs/std_log_process_1.txt read similarly 
```
Filesystem     1024-blocks    Used Available Capacity Mounted on
overlay          700716496 3153904 661894728       1% /
Cleaning up all outstanding Run operations, waiting 300.0 seconds
1 items cleaning up...
Cleanup took 0.04425811767578125 seconds
Traceback (most recent call last):
  File "source_file.py", line 170, in <module>
    startRay(master_ip)
  File "source_file.py", line 145, in startRay
    time.sleep(1)
  File "/azureml-envs/azureml_5c300eadea2c0e7ca519e1a7506ec147/lib/python3.10/site-packages/ray/_private/worker.py", line 1640, in sigterm_handler
    sys.exit(signum)
SystemExit: 15
```

**Comment by hyssh** [comment]
@coledie I have two questions for you. 
1 Can you share the result of command `ray.cluster_resources()`?
2 Is CI (which is configured as the Head node of the cluster) in the same VNet where CC (Compute Cluster) is provisioned?

**Comment by coledie** [comment]
@hyssh 
1. Cluster resources: {'memory': 2350532199.0, 'object_store_memory': 1175266099.0, 'node:172.24.154.65': 1.0, 'CPU': 8.0}
2. I only start one cluster // run the script one time in one with one config.json file so yes.

**Comment by coledie** [comment]
Resolved by setting up VNet and Network Security group with https://learn.microsoft.com/en-us/azure/machine-learning/how-to-secure-training-vnet?view=azureml-api-2&tabs=cli%2Crequired
